apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::648911607072:role/wsc2024-role-externalsecrets
  name: externalsecrets
  namespace: wsc2024
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-sample
  namespace: wsc2024
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: externalsecrets
---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secretstore-sample
  namespace: wsc2024
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  target:
    name: dbsecret
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: wsc2024-db-secret
      property: password
  - secretKey: user
    remoteRef:
      key: wsc2024-db-secret
      property: user
  - secretKey: host
    remoteRef:
      key: wsc2024-db-secret
      property: host
  - secretKey: port
    remoteRef:
      key: wsc2024-db-secret
      property: port
  - secretKey: dbname
    remoteRef:
      key: wsc2024-db-secret
      property: dbname
