apiVersion: gateway.networking.k8s.io/v1beta1

kind: GatewayClass
metadata:
  name: amazon-vpc-lattice
spec:
  controllerName: application-networking.k8s.aws/gateway-api-controller
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: wsc2024-lattice-svc-net
  namespace: wsc2024
spec:
  gatewayClassName: amazon-vpc-lattice
  listeners:
    - name: http
      protocol: HTTP
      port: 80
---
apiVersion: application-networking.k8s.aws/v1alpha1
kind: TargetGroupPolicy
metadata:
  name: wsc2024-policy
  namespace: wsc2024
spec:
  targetRef:
    group: ""
    kind: Service
    name: customer-service
  protocol: HTTP
  protocolVersion: HTTP1
  healthCheck:
    enabled: true
    intervalSeconds: 10
    timeoutSeconds: 1
    healthyThresholdCount: 3
    unhealthyThresholdCount: 2
    path: "/health"
    port: 8080
    protocol: HTTP
    protocolVersion: HTTP1
    statusMatch: "200"
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: wsc2024-route
  namespace: wsc2024
spec:
  parentRefs:
    - name: wsc2024-lattice-svc-net
      sectionName: http
  rules:
    - backendRefs:
        - name: customer-service
          namespace: wsc2024
          kind: Service
          port: 8080
